#nullable enable
// AthRemoteSettings — the editor half of the two-lock design. A Project
// Settings panel + Tools menu toggle that, for the ACTIVE build target:
//   - adds/removes the ATH_REMOTE scripting define (compile-time master enable), and
//   - writes/removes a link.xml that preserves the harness's reflection-invoked
//     [ConsoleMethod]s + types from IL2CPP managed stripping in a non-dev build.
// Off => neither present => a true release build has zero harness footprint.
// (Live-verify lesson from the first BTS RC build: without the link.xml, High
// managed stripping removes the harness even though ATH_REMOTE is defined.)

using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEngine;

namespace LlamaBrainLabs.Ath.Editor
{
    internal static class AthRemoteSettings
    {
        private const string Define   = "ATH_REMOTE";
        private const string MenuPath = "Tools/ATH/Remote Console (ATH_REMOTE)";
        private const string LinkDir  = "AthRemoteHarness";
        private const string LinkFile = "link.xml";

        private const string LinkXml =
@"<!-- Generated by the ATH Remote Console toggle. Preserves the exe-harness
     assemblies (whose [ConsoleMethod]s are invoked only via reflection) from
     IL2CPP managed stripping in an ATH_REMOTE build. Deleted when toggled off. -->
<linker>
  <assembly fullname=""LlamaBrainLabs.Ath.Runtime"" preserve=""all"" />
  <assembly fullname=""LlamaBrainLabs.Ath.Commands"" preserve=""all"" />
  <assembly fullname=""LlamaBrainLabs.Ath.RemoteConsole.Runtime"" preserve=""all"" />
</linker>
";

        private static NamedBuildTarget ActiveTarget =>
            NamedBuildTarget.FromBuildTargetGroup(
                BuildPipeline.GetBuildTargetGroup(EditorUserBuildSettings.activeBuildTarget));

        private static bool IsEnabled(NamedBuildTarget t)
        {
            foreach (var d in PlayerSettings.GetScriptingDefineSymbols(t).Split(';'))
                if (d.Trim() == Define) return true;
            return false;
        }

        private static void SetEnabled(NamedBuildTarget t, bool on)
        {
            var defs = new List<string>(PlayerSettings.GetScriptingDefineSymbols(t).Split(';'));
            defs.RemoveAll(d => d.Trim() == Define || string.IsNullOrWhiteSpace(d));
            if (on) defs.Add(Define);
            PlayerSettings.SetScriptingDefineSymbols(t, string.Join(";", defs));
            if (on) WriteLink(); else RemoveLink();
        }

        // ---- link.xml in the host's Assets/ ----
        private static string LinkFolderAbs => Path.Combine(Application.dataPath, LinkDir);
        private static string LinkPathAbs   => Path.Combine(LinkFolderAbs, LinkFile);

        private static void WriteLink()
        {
            Directory.CreateDirectory(LinkFolderAbs);
            File.WriteAllText(LinkPathAbs, LinkXml);
            AssetDatabase.Refresh();
        }

        private static void RemoveLink()
        {
            try
            {
                if (File.Exists(LinkPathAbs))           File.Delete(LinkPathAbs);
                if (File.Exists(LinkPathAbs + ".meta"))  File.Delete(LinkPathAbs + ".meta");
                if (Directory.Exists(LinkFolderAbs) && Directory.GetFiles(LinkFolderAbs).Length == 0)
                    Directory.Delete(LinkFolderAbs);
                if (File.Exists(LinkFolderAbs + ".meta")) File.Delete(LinkFolderAbs + ".meta");
            }
            catch { /* best effort */ }
            AssetDatabase.Refresh();
        }

        // ---- Tools menu shortcut ----
        [MenuItem(MenuPath, false)]
        private static void Toggle() => SetEnabled(ActiveTarget, !IsEnabled(ActiveTarget));

        [MenuItem(MenuPath, true)]
        private static bool ToggleValidate()
        {
            Menu.SetChecked(MenuPath, IsEnabled(ActiveTarget));
            return true;
        }

        // ---- Project Settings ▸ ATH Remote ----
        [SettingsProvider]
        public static SettingsProvider Provider()
        {
            return new SettingsProvider("Project/ATH Remote", SettingsScope.Project)
            {
                label = "ATH Remote",
                keywords = new HashSet<string>(new[] { "ATH", "remote", "console", "harness", "exe", "ATH_REMOTE", "link.xml" }),
                guiHandler = _ =>
                {
                    var t = ActiveTarget;
                    EditorGUILayout.HelpBox(
                        $"Modifying the ACTIVE build target: {t.TargetName}. ATH_REMOTE bakes the " +
                        "exe remote-console harness into this target's builds (dev OR non-dev release) " +
                        "and writes a link.xml so IL2CPP stripping can't remove it.",
                        MessageType.Info);

                    bool on = IsEnabled(t);
                    bool newOn = EditorGUILayout.ToggleLeft($"Enable ATH_REMOTE for {t.TargetName}", on);
                    if (newOn != on) SetEnabled(t, newOn);

                    EditorGUILayout.Space();
                    EditorGUILayout.LabelField("Authoring defaults (ProjectSettings/AthRemote.json)", EditorStyles.boldLabel);
                    var cfg = AthRemoteConfig.Load();
                    EditorGUI.BeginChangeCheck();
                    cfg.port      = EditorGUILayout.IntField("Port", cfg.port);
                    cfg.mediaDir  = EditorGUILayout.TextField("Media dir (blank = persistentDataPath)", cfg.mediaDir);
                    cfg.timeoutMs = EditorGUILayout.IntField("Response timeout (ms)", cfg.timeoutMs);
                    if (EditorGUI.EndChangeCheck()) cfg.Save();

                    EditorGUILayout.Space();
                    EditorGUILayout.HelpBox(
                        "Host requirement for non-dev RC builds: a host adapter gated on " +
                        "UNITY_EDITOR || DEVELOPMENT_BUILD must also add || ATH_REMOTE, or " +
                        "harness.state reports adapter_present=false.",
                        MessageType.Warning);
                },
            };
        }
    }
}
